package util;

import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;

public class EmailService {

    // --- YOUR CREDENTIALS ---
    private static final String SENDER_EMAIL = "clubsphere.umt2026@gmail.com";
    private static final String SENDER_PASSWORD = "rpvgliwsyehohlyk";

    // 1. Send Appointment Email (New Members/Committee)
    public static boolean sendPasswordEmail(String recipientEmail, String userName, String tempPassword, String role, String clubName) {
        System.out.println(">>> Attempting to send appointment email to: " + recipientEmail);
        return sendEmail(recipientEmail, "UMT ClubSphere - Appointment as " + formatRole(role),
                generateAppointmentHtml(userName, tempPassword, role, clubName, recipientEmail));
    }

    // 2. Send OTP Email (Forgot Password)
    public static void sendOTPEmail(String recipientEmail, String otp) {
        System.out.println(">>> Attempting to send OTP email to: " + recipientEmail);

        String subject = "Password Reset OTP - UMT ClubSphere";
        String htmlContent = "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #eee; padding: 20px; border-radius: 10px;'>"
                + "<h2 style='color: #0d6efd; text-align: center;'>UMT ClubSphere</h2>"
                + "<h3>Password Reset Verification</h3>"
                + "<p>Hello,</p>"
                + "<p>We received a request to reset your password. Use the following 6-digit code to verify your identity. This code is valid for 10 minutes.</p>"
                + "<div style='background: #f8f9fa; padding: 20px; text-align: center; border-radius: 10px; margin: 20px 0;'>"
                + "<h1 style='letter-spacing: 10px; color: #333; margin: 0;'>" + otp + "</h1>"
                + "</div>"
                + "<p style='color: #666; font-size: 12px;'>If you did not request this, please ignore this email or contact support if you have concerns.</p>"
                + "<hr style='border: 0; border-top: 1px solid #eee;'>"
                + "<p style='text-align: center; font-size: 11px; color: #999;'>&copy; 2026 UMT ClubSphere - Student Management System</p>"
                + "</div>";

        // Call the common send method using the CORRECT credentials
        new Thread(() -> {
            sendEmail(recipientEmail, subject, htmlContent);
        }).start();
    }

    // ========================================================
    // 3. FUNGSI BARU: HANTAR NOTIFIKASI UMUM (GENERAL ALERT)
    // ========================================================
    public static void sendGeneralNotification(String recipientEmail, String recipientName, String alertTitle, String alertMessage) {
        String subject = "ClubSphere Alert: " + alertTitle;

        String htmlContent = "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 10px; overflow: hidden;'>"
                + "<div style='background-color: #0d47a1; padding: 20px; text-align: center; color: white;'>"
                + "<h2 style='margin: 0;'>ClubSphere System Alert</h2>"
                + "</div>"
                + "<div style='padding: 30px; background-color: #f9f9f9;'>"
                + "<p style='font-size: 16px; color: #333;'>Hello <strong>" + recipientName + "</strong>,</p>"
                + "<p style='font-size: 16px; color: #555;'>You have a new notification regarding your club activities:</p>"
                + "<div style='background-color: #fff; padding: 15px; border-left: 4px solid #ffc107; border-radius: 5px; margin: 20px 0; box-shadow: 0 2px 5px rgba(0,0,0,0.05);'>"
                + "<h3 style='margin-top: 0; color: #333;'>" + alertTitle + "</h3>"
                + "<p style='margin-bottom: 0; color: #666;'>" + alertMessage + "</p>"
                + "</div>"
                + "<p style='font-size: 14px; color: #777;'>Please log in to your <a href='#' style='color: #0d47a1; font-weight: bold;'>ClubSphere Dashboard</a> to view details and take necessary actions.</p>"
                + "</div>"
                + "<div style='background-color: #eee; padding: 15px; text-align: center; font-size: 12px; color: #888;'>"
                + "This is an automated message generated by UMT ClubSphere. Please do not reply."
                + "</div>"
                + "</div>";

        new Thread(() -> {
            sendEmail(recipientEmail, subject, htmlContent);
        }).start();
    }

    // --- SHARED SEND METHOD (To reuse credentials correctly) ---
    private static boolean sendEmail(String recipientEmail, String subject, String htmlContent) {
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.ssl.trust", "smtp.gmail.com");

        Session session = Session.getInstance(props, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                // FIXED: Uses the constants declared at top
                return new PasswordAuthentication(SENDER_EMAIL, SENDER_PASSWORD);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(SENDER_EMAIL, "UMT ClubSphere Admin"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recipientEmail));
            message.setSubject(subject);
            message.setContent(htmlContent, "text/html; charset=utf-8");

            Transport.send(message);
            System.out.println("✅ SUCCESS: Email sent to " + recipientEmail);
            return true;

        } catch (Exception e) {
            System.err.println("❌ ERROR: Could not send email to " + recipientEmail);
            e.printStackTrace();
            return false;
        }
    }

    // --- HTML GENERATOR FOR APPOINTMENT ---
    private static String generateAppointmentHtml(String userName, String tempPassword, String role, String clubName, String email) {
        String displayRole = formatRole(role);
        return "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;'>"
                + "  <div style='background-color: #0d6efd; padding: 20px; text-align: center; color: white;'>"
                + "    <h2 style='margin: 0;'>Official Appointment</h2>"
                + "  </div>"
                + "  <div style='padding: 20px; color: #333;'>"
                + "    <p>Dear <strong>" + userName + "</strong>,</p>"
                + "    <p>Congratulations! You have been officially appointed as <strong>" + displayRole + "</strong> for <strong>" + clubName + "</strong>.</p>"
                + "    <p>To access your administrative dashboard, please use the following credentials:</p>"
                + "    <div style='background-color: #f8f9fa; padding: 15px; border-left: 4px solid #0d6efd; margin: 20px 0;'>"
                + "      <p style='margin: 5px 0;'><strong>Username:</strong> " + email + "</p>"
                + "      <p style='margin: 5px 0;'><strong>Password:</strong> <span style='font-size: 1.2em; font-weight: bold; font-family: monospace; letter-spacing: 1px; color: #d63384;'>" + tempPassword + "</span></p>"
                + "    </div>"
                + "    <p>Please log in and change your password immediately.</p>"
                + "    <br>"
                + "    <p style='font-size: 0.9em; color: #666;'>Regards,<br><strong>Majlis Perwakilan Pelajar (MPP)</strong><br>Universiti Malaysia Terengganu</p>"
                + "  </div>"
                + "  <div style='background-color: #f1f1f1; padding: 10px; text-align: center; font-size: 0.8em; color: #888;'>"
                + "    &copy; 2026 UMT ClubSphere. All rights reserved."
                + "  </div>"
                + "</div>";
    }

    private static String formatRole(String code) {
        if (code == null) {
            return "Member";
        }
        switch (code) {
            case "Pres":
                return "Club President";
            case "Vice Pres":
                return "Vice President";
            case "Secr":
                return "Secretary";
            case "Treas":
                return "Treasurer";
            default:
                return code;
        }
    }
}
